protocolVersion: 2
name: pytorch_mnist
type: job
version: 1.0.0
contributor: OpenPAI
description: image classification, mnist dataset, pytorch

parameters:
  epochs: 10
  batchsize: 32
  lr: 0.01

prerequisites:
  - protocolVersion: 2
    name: pytorch_example
    type: dockerimage
    version: 1.0.0
    contributor : OpenPAI
    description: python3.5, pytorch
    uri : openpai/pai.example.pytorch

taskRoles:
  worker:
    instances: 1
    completion:
      minSucceededTaskCount: 1
    dockerImage: pytorch_example
    resourcePerInstance:
      cpu: 4
      memoryMB: 8192
      gpu: 1
    commands:
      - >
        python pytorch_examples/mnist/main.py
        --epochs <% $parameters.epochs %>
        --lr <% $parameters.epochs %>
        --batch-size <% $parameters.epochs %>
